import React from "react";
import second from "../../../../assets/second.png";
import eyeIcon from "../../../../assets/eye.png";
import magic from "../../../../assets/magic.png";
import download from "../../../../assets/download.png";

const work = [
   {
      title: "Describe your Vision",
      description:
         "Provide us your vision about your investments in the business and get decisions about the profits.",
      icon: eyeIcon,
   },
   {
      title: "Watch the Magical result",
      description:
         "Get unique, accurate, and highly effective prompts generated by Fin Prompt Ai.",
      icon: magic,
   },
   {
      title: "Get Investment profit from AI",
      description:
         "Our Fin Prompt Ai provides highly personalized and accurate financial prompts looking at your investments and vision.",
      icon: download,
   },
];
const HowWorks = () => {
   return (
      <>
         <section
            className="relative h-[70vh] md:h-[100vh] w-full bg-cover bg-center before:absolute before:inset-0 before:bg-black before:opacity-50 border-t-gray-500 mt-0.4"
            style={{ backgroundImage: `url(${second})` }}>
            <h1 className="text-white relative z-2 top-18 text-center text-2xl md:text-4xl font-[Lato]">
               How it works?
            </h1>

            <div className="flex flex-col items-center justify-center relative z-2 mt-24 gap-5 md:gap-10 md:mt-30">
               {work.map((data, i) => (
                  <div
                     className="bg-white rounded-2xl flex p-3 md:px-7 gap-5 md:gap-6 justify-center items-center"
                     key={i}
                  >
                     <img src={data.icon} alt="" className="size-10 md:size-15" />
                     <div>
                        <h3 className="text-[#2B2B2B] font-black text-sm md:text-xl">
                           {data.title}
                        </h3>
                        <p className="text-[#2B2B2B] font-normal text-xs md:w-xl md:text-lg">
                           {data.description}
                        </p>
                     </div>
                  </div>
               ))}
            </div>
         </section>
      </>
   );
};

export default HowWorks;

